# Generated by Django 5.0.14 on 2026-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
