# Generated by Django 6.0.3 on 2026-04-26 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('comparisons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.ManyToManyField(related_name='favorited_in_sets', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное сравнение',
                'verbose_name_plural': 'Избранные сравнения',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'products_hash')},
            },
        ),
    ]
