# Generated by Django 5.2.7 on 2025-11-22 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_as_first', to='compare.product')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_as_second', to='compare.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная пара',
                'verbose_name_plural': 'Избранные пары',
                'unique_together': {('user', 'product_1', 'product_2')},
            },
        ),
    ]
