# Generated by Django 5.2.7 on 2025-12-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_product_img_characteristicgroup_characteristic_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={},
        ),
        migrations.CreateModel(
            name='CharacteristicTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название характеристики')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='compare.characteristicgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Характеристика (шаблон)',
                'verbose_name_plural': 'Характеристики (шаблоны)',
                'ordering': ['order'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='compare.product', verbose_name='Товар')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='compare.characteristictemplate', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
    ]
