# Generated by Django 5.2.7 on 2025-12-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20251206_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicgroup',
            unique_together={('category', 'name')},
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
