# Generated by Django 5.2.7 on 2026-05-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicvalue',
            unique_together={('product', 'template')},
        ),
    ]
