# Generated by Django 5.2.7 on 2026-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_characteristicvalue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicgroup',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='characteristictemplate',
            unique_together={('group', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название группы характеристик'),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название группы характеристик'),
        ),
        migrations.AddField(
            model_name='characteristictemplate',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='characteristictemplate',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='characteristicgroup',
            unique_together={('category', 'name'), ('category', 'name_en'), ('category', 'name_ru')},
        ),
        migrations.AlterUniqueTogether(
            name='characteristictemplate',
            unique_together={('group', 'name'), ('group', 'name_en'), ('group', 'name_ru')},
        ),
    ]
