# Generated by Django 5.2.7 on 2026-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_characteristicgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicvalue',
            name='value_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='value_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение'),
        ),
    ]
