# Generated by Django 6.0.3 on 2026-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_name_en_category_name_ru'),
        ('characteristic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristicgroup',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='characteristictemplate',
            unique_together={('group', 'name')},
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название группы характеристик'),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название группы характеристик'),
        ),
        migrations.AddField(
            model_name='characteristictemplate',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='characteristictemplate',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название характеристики'),
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='value_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='value_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Значение'),
        ),
        migrations.AlterUniqueTogether(
            name='characteristicgroup',
            unique_together={('category', 'name'), ('category', 'name_en'), ('category', 'name_ru')},
        ),
        migrations.AlterUniqueTogether(
            name='characteristictemplate',
            unique_together={('group', 'name'), ('group', 'name_en'), ('group', 'name_ru')},
        ),
    ]
