# Generated by Django 5.0.14 on 2026-04-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_name_en_category_name_ru'),
        ('characteristic', '0002_alter_characteristicgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicgroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='char_groups', to='categories.category', verbose_name='Категория'),
        ),
    ]
